/**
 * Writes web/config.js from LEXINTAKE_API_URL (Vercel env) at build time.
 */
const fs = require("fs");
const path = require("path");

const apiUrl = (process.env.LEXINTAKE_API_URL || "").replace(/\/$/, "");
const out = path.join(__dirname, "config.js");
const body = `/* generated by web/build-config.js */\nwindow.LEXINTAKE_API_URL = ${JSON.stringify(apiUrl)};\n`;
fs.writeFileSync(out, body, "utf8");
console.log(`Wrote ${out} (API URL ${apiUrl ? "set" : "empty"})`);
